### PR TITLE
Removed -s, added libcurl and upgraded ldc

### PR DESCRIPTION
**Pull request by DiddiZ**
Fixes for open issues and upgraded ldc to v1.5.0-beta1.

### CODE REVIEW

**Comment by jondegenhardt** [comment]
Thanks for making the PR, I'm could use an updated release as well.

There's one more addition needed by the 1.5 release, that's for `cmake`. It's needed by the new `ldc-build-runtime` tool (which also needs `libcurl` which you added.) Would you be willing to add `cmake` to your PR? It can be added right after the `gcc` install, as
```
 && apt-get install -y cmake \
```

If you'd prefer not to change the PR I can submit it separately.

**Comment by jondegenhardt** [comment]
LDC 1.5.0 final may be out relatively soon, may want to wait for that: [ldc/issues/2369](https://github.com/ldc-developers/ldc/issues/2369#issuecomment-340207041)

**Comment by DiddiZ** [comment]
Sure, can do.

**Comment by DiddiZ** [comment]
@jondegenhardt I haven't worked with `ldc-build-runtime` yet. Can you verify whether it works properly?

**Comment by jondegenhardt** [comment]
@DiddiZ Thanks. Tried your change, it worked fine. You try it yourself by running `ldc-build-runtime` with no arguments. Start the container and run the command:
```
$ docker run --rm -ti -v $(pwd):/src <docker-image> /bin/bash
# ldc-build-runtime
```
Or start by running the command:
```
$ docker run --rm -ti -v $(pwd):/src <docker-image> ldc-build-runtime
```

The command downloads the druntime and phobos source specific to the LDC release and builds it. It uses `curl` and `cmake` to do this. I'm using it for the new capability to build druntime/phobos with LTO, so I use a command like `ldc-build-runtime --dFlags="-flto=full"`.

**Comment by jondegenhardt** [comment]
LDC 1.5.0 is now out: [Release v1.5.0](https://github.com/ldc-developers/ldc/releases/tag/v1.5.0)

**Comment by lindt** [comment]
thank you guys!

**Comment by jondegenhardt** [comment]
Very timely! I need to use ldc 1.5 / Ubuntu 16.04 on Travis-Ci. Travis doesn’t support 16.04 yet, this docker image is the best way I’ve found to get the combo. Thanks!

**Comment by jondegenhardt** [comment]
@lindt It looks like this was switched back to using 1.5.0-beta1. I'm hoping you can switch this back to 1.5.0. The reason it matters is that there were some compiler switch changes between the beta1 and final releases, they aren't backward compatible. These were switches introduced in the beta1 release, so they are orphans now.

**Pull request merged**
